[package]
name = "fast_woothee"
version = "1.0.2"
authors = ["Ian Ker-Seymer <i.kerseymer@gmail.com>"]
repository = "https://github.com/ianks/fast_woothee"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
woothee = "^0.6"
ruru = "^0.9"


[package.metadata.thermite]
github_releases = true
optional_rust_extension = true
